### ISSUE TITLE
Component not recognized

### ISSUE THREAD

**Issue by youfoundron** [enki-com/react-search-input#1]
The returned object does not seem to be recognized as a react component. 

As soon as I include it and attempt to use it as a component I am met with: 

`Uncaught TypeError: Can't add property context, object is not extensible`

preceded by the warning:

`Warning: Component(...): No `render` method found on the returned component instance: you may have forgotten to define `render` in your component or you may have accidentally tried to render an element whose type is a function that isn't a React component.`

Below is my implementation (cjsx):

```
React = require 'react'

# Components
AddList = require './addlist.cjsx'
SearchInput = require 'react-search-input'

SearchFollowers = React.createClass
  searchUpdated: (term) ->
    @setState {searchTerm: term} # needed to force re-render

  render: ->
    filtered_followers = _.cloneDeep @props.followers
    if @refs.search
      filters = ['username', 'full_name']
      filtered_followers = filtered_followers.filter(@refs.search.filter(filters))

    return (
      <div className="search">
        <SearchInput ref='search' onChange={@searchUpdated} />
        <AddList user={@props.user} followers={filtered_followers} handleLike={@props.handleLike}/>
      </div>
    )
```

Pointing out some oversight on my part would be greatly appreciated.

**Comment by mathieudutour** [comment]
It was probably because of a different version of react, I assumed that you were using React 0.13 while this was fetching 0.12. 

This should be fixed. 

Could you try again (you might need to delete your node_modules folder)?

**Comment by youfoundron** [comment]
Yeah definitely a versioning issue, I implemented the component locally with -- for the most part -- the same code as you and it worked fine. Thank you for the prompt response!
