### ISSUE TITLE
not working for regex objects

### ISSUE THREAD

**Issue by mashehu** [enki-com/react-search-input#120]
If I use regex objects as search terms it fails, because regex does not have .toLowerCase() or .split() methods, which are used in the filter/createFilter methods of this component.

**Comment by mathieudutour** [comment]
hum, you can just use the "inside" of the regex. But yeah we could check if it's a regex.

Happy to accept a PR

**Comment by mashehu** [comment]
hmm, is it currently possible to enforce an exact match? Since I didn't see it specified anywhere, I thought I can get that be using regex.

I will check if I can get a better regex implementation running.
