### ISSUE TITLE
Update for React 16?

### ISSUE THREAD

**Issue by Nantris** [enki-com/react-search-input#129]
Unfortunately it doesn't seem to work in React 16. Any chance of an update?

**Comment by Nantris** [comment]
My mistake. It does seem to work.

**Comment by VrajSolanki** [comment]
@Slapbox Can you tell me how is it working for you in React 16

**Comment by Nantris** [comment]
Works fine. No issues.

**Comment by VrajSolanki** [comment]
@Slapbox On updating my react to v16, I start getting this error:
Uncaught TypeError: (0 , _reactSearchInput.createFilter) is not a function
