### ISSUE TITLE
Change or remove placeholder

### ISSUE THREAD

**Issue by ChristianTheMinery** [enki-com/react-search-input#135]
Currently, there doesn't seem to be any way to replace or remove the 'Search' placeholder attribute. This feature would be greatly appreciated!

**Comment by mathieudutour** [comment]
just use the `placeholder` prop?

**Comment by ChristianTheMinery** [comment]
The placeholder prop doesn't accept an empty string (or null, or false) if I don't want a placeholder, but instead defaults back to 'Search'.

**Comment by mathieudutour** [comment]
probably because the default type of the input is `search`. Change it to `text` and there shouldn't be anything

**Comment by ChristianTheMinery** [comment]
No dice - I believe the issue would be on line 46 of index.js:

`inputProps.placeholder = inputProps.placeholder || 'Search'`

Seeing as an empty string is a falsey value, this line will return 'Search' if an empty string is passed.

I can get around the issue by passing a string that contains a space, which no longer evaluates as empty.
