### ISSUE TITLE
Not working with React 16

### ISSUE THREAD

**Issue by VrajSolanki** [enki-com/react-search-input#136]
Version: 0.31.0
The component does not work with updating react to version 16. 

> error: Uncaught TypeError: (0 , _reactSearchInput.createFilter) is not a function, 

If I create without using the createFilter, like the example index.html I get 

> error: Uncaught TypeError: this.updater.enqueueCallback is not a function

I feel this component is not working for react 16.
Can you please look into it.

**Comment by mishawakerman** [comment]
This appears to now be fixed in `v0.11.3`.
