### ISSUE TITLE
Github banner obscures demo

### ISSUE THREAD

**Issue by winkler1** [enki-com/react-search-input#2]
Hi-
 Am looking at this for react.rocks. Looks good, but the banner covers the search area--

![image](https://cloud.githubusercontent.com/assets/883896/7960313/a68ad13a-09cd-11e5-801e-308bcb2e1185.png)

 Could it be moved to the right-hand side instead? 
Thanks!
Jeff

**Comment by mathieudutour** [comment]
Yeah i was just being lazy. 

Done.
