### ISSUE TITLE
can I get multi result with multi key with same type?

### ISSUE THREAD

**Issue by nhuutri2** [enki-com/react-search-input#56]
It's work well, but i have a question
Example: I have a list book object have type: 1, type:2, type:3,... . Can I get results with books have type:1, type:2 ?

Thanks

**Comment by mathieudutour** [comment]
I'm sorry i'm not sure I understand.

You have 

```
[{
  a: string,
  b: string,
  c: string
}]
```

and you want to search in `a` and `b` ?

Then you can search for `a:query b:query`.
