### ISSUE TITLE
Enhancement in "getValuesForKey" to support flattened keys with array indexes

### ISSUE THREAD

**Issue by jpinho** [enki-com/react-search-input#57]
In this part of the code, inside the function `getValuesForKey`

```
if (result instanceof Array) {
          result.forEach(function (res) {
            tmp.push(res[_key]); <--- HERE // res is not the index is the item
          });
        }
...
```

We should change that line to `tmp.push(res)`. As it is at the moment, searching inside an object like this:

```
{ a: { b: { test: [ { abc: "hello" } ] }} }
```

with the key `a.b.test.0.abc` will fail.

PR here #58

**Comment by mathieudutour** [comment]
hum, the way I did it is that you would use the key `a.b.test.abc` so you can search the entire array.

I think what we want is something like this:

``` js
if (result instanceof Array) {
  const index = parseInt(_key, 10);
  if (!isNaN(index)) {
    return tmp.push(result[index]);
  }
  result.forEach(function (res) {
    tmp.push(res[_key]);
  });
}
```

right?

**Comment by jpinho** [comment]
Ah ok, makes sense to me now!

Yes good idea, checking if `key` is a number seems better, that way it supports both scenarios: flattened key with index and without it.
