### ISSUE TITLE
Make component React 15.2.x compliant

### ISSUE THREAD

**Issue by seethroughdev** [enki-com/react-search-input#61]
Upgrading to React 15.2 gives the warning:

`warning.js:44Warning: Unknown prop `fuzzy` on <input> tag. Remove this prop from the element. ...`

More info is available here: https://gist.github.com/jimfb/d99e0678e9da715ccf6454961ef04d1b.

If you're accepting PRs, I can probably make one in the next day or two.  Otherwise, would love to see this update.

Thanks!

**Comment by mathieudutour** [comment]
I definitively accept PRs. If you don't have time, I might be able to find some next week.
