### ISSUE TITLE
Programmatically Focus on React-Search-Input?

### ISSUE THREAD

**Issue by Nantris** [enki-com/react-search-input#79]
I'm trying to programmatically focus on the input but it doesn't seem to be do-able in any reasonable straightforward way. This would be great to have.

**Comment by Nantris** [comment]
Solution: http://stackoverflow.com/a/39231166/6025788

**Comment by mathieudutour** [comment]
missed it sorry. Yeah you need to get the DOM node. I'm not sure what would be a better solution

**Comment by mathieudutour** [comment]
closing for now but happy to hear your thoughs
