### ISSUE TITLE
Debounce?

### ISSUE THREAD

**Issue by wle8300** [enki-com/react-search-input#82]
Any plans to add a debounce option? It allows some delay time after hitting a key before it begins filtering.

**Comment by mathieudutour** [comment]
It is already throttled.
What is your use case for debouce?

**Comment by wle8300** [comment]
Oh I didn't know that. I haven't tried it out yet, but other similar modules have the option to explicitly set the throttle ms. Thanks for the help!

**Comment by mathieudutour** [comment]
you can with this one also with the `throttle` prop :)

**Comment by wle8300** [comment]
Ugh. I'm so lame sometimes. I didn't even see that! Thx again!
