### ISSUE TITLE
Clearing the field with Ctrl+A and Delete or Ctrl+Z after entering a term does not update the searchterm variable.

### ISSUE THREAD

**Issue by Nantris** [enki-com/react-search-input#87]

**Comment by mathieudutour** [comment]
it does here: https://enkidevs.github.io/react-search-input/. Do you have an example?

**Comment by Nantris** [comment]
Ah great thanks for a reference site! The problem is almost definitely in my code then. Probably in my interfacing of this with Redux. Thanks very much!

**Comment by Nantris** [comment]
Confirmed that the problem is with my own code.
